# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

1. Crear un arreglo de ceros de longitud 12

In [2]:
print(np.zeros(12))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [3]:
arreglo2=np.zeros(10)
arreglo2[9]=5
print(arreglo2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]


3. Crear un arreglo que tenga los números del 10 al 49


In [7]:
arreglo3=np.arange(10,50)
print(arreglo3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [16]:
lista4= [[0,1,2],[3,4,5],[6,7,8]]
arreglo4 = np.array(lista4)
print(arreglo4)
print(arreglo4.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y su varianza

In [30]:
arreglo5 = np.random.randint(0,100,100)
print(arreglo5)
print(f'El valor medio es', np.mean(arreglo5))
print(f'La varianza es', np.var(arreglo5))

[89 26  1 98 60 14 60 22 10 21 22  5 28 10 90 36 52 57 69 44 58 19 23 31
 99 97 70 46 91 22 14 54 14 37 51 62 75 40 81 16 99 20 33 85  0 46  0 42
 15 27 14 75  3 50 27 36 74 58 39 12 38 55 43 58 63  6 62 15 92 24 16 31
 33 75 38 22 58 49 51 12 92 51 89 20  2 71 10 77 56 35 96  5 56 23 92 63
 62 98  9  8]
El valor medio es 44.25
La varianza es 827.5275


6. Calcular la media de un arreglo usando np.sum

In [34]:
arreglo6 = np.random.randint(0,100,100)
media= np.sum(arreglo6)/100
print(f'El valor medio con con la función mean es', np.mean(arreglo6))
print(f'El valor medio con la función sum es', media)

El valor medio con con la función mean es 46.84
El valor medio con la función sum es 46.84


7. Calcular la varianza con np.sum y np.mean

In [43]:
arreglo7 = np.random.randint(0,100,100)
diferencias_al_cuadrado=(arreglo7-np.mean(arreglo7))**2
varianza=np.sum(diferencias_al_cuadrado)/100
print(f'El valor de la varianza con la función np.sum y np.mean es', varianza)
print(f'El valor de la varianza con la función np.var es', np.var(arreglo7))

El valor de la varianza con la función np.sum y np.mean es 714.8874999999998
El valor de la varianza con la función np.var es 714.8874999999998


8. Crear un arreglo de números aleatorios usando la función np.random.randn

In [45]:
print(np.random.rand(5))

[0.33350583 0.6309571  0.1330216  0.90335103 0.19177197]
